### ISSUE TITLE
A few small things

### ISSUE THREAD

**Issue by b-t-k** [ConcaveTrillion/hilaire-belloc_the-mercy-of-allah#2]
## Modernize
Bab-El vs Bab-el vs Babel
- I see why you wouldn't accept the modernization, but I would consider regularizing them to Bab El Xxx since that's what  most of them seem to use in modern nomenclature. But that's based on some hasty research...

## Dedication
Should be z3998 non-fiction

## content.opf
Add a bit more to the long description? Belloc was such an interesting guy. Perhaps where *The Mercy of Allah* fits in his canon or its publication history?

**Comment by ConcaveTrillion** [comment]
Dedication fixed. Added a bit more to the long description.

As for Bab, it seems to mean "Gate" and seems in modern usage the hyphen is sometimes kept and sometimes not. I don't think it matters too much, given Belloc's playing *very* fast and loose with the 'Arabian' setting anyway.

https://en.wikipedia.org/wiki/Bab-el-Mandeb
https://en.wikipedia.org/wiki/Bab_El_Oued
https://en.wikipedia.org/wiki/Bab_el-Gasus
